### ISSUE TITLE
Docker Pull Error

### ISSUE THREAD

**Issue by Borlean** [aliparlakci/bulk-downloader-for-reddit#153]
When creating the container via docker yml file, receiving the following error message:

ERROR: The image for the service you're trying to recreate has been removed. If you continue, volume data could be lost. Consider backing up your data before continuing.

Continue with the new image? [yN]y
Pulling bdfr (bdfr:)...
ERROR: pull access denied for bdfr, repository does not exist or may require 'docker login'

YML File:

```
version: '3'

########################### NETWORKS
networks:
  default:
    external:
      name: $DEFAULT_NETWORK

########################### Services
services:
# All services / apps go below this line

  bdfr:
# Bulk Downloader for Reddit
    image: bdfr
    container_name: bdfr_container
    ports:
      - "8080:8080"
      - "7634:7634"
    environment:
      - PUID
      - PGID
      - TZ
    volumes:
      - "./:/root/Bulk Downloader for Reddit"
    restart: always
    network_mode: bridge 
```
